ARG LMDEPLOY_VERSION=0.6.1.1

# Stage 1: Build the WHL file
FROM nvcr.io/nvidia/pytorch:25.01-py3 AS builder

# Ubuntu 24.04 including Python 3.12
# NVIDIA CUDA 12.8.0.038
# NVIDIA cuBLAS 12.8.3.14
# NVIDIA cuDNN 9.7.0.66
# NVIDIA NCCL 2.25.1
# NVIDIA RAPIDS™ 24.10
# rdma-core 50.0
# NVIDIA HPC-X 2.21
# SHARP 3.9.0
# UCC 1.4.0
# OpenUCX 1.18.0
# OpenMPI 4.1.7
# GDRCopy 2.4.1
# TensorBoard 2.16.2
# Nsight Compute 2025.1.0.14
# Nsight Systems 2024.6.2.225
# NVIDIA TensorRT™ 10.8.0.40
# Torch-TensorRT 2.6.0a0
# NVIDIA DALI® 1.45
# nvImageCodec 0.2.0.7
# MAGMA 2.6.2
# JupyterLab 4.3.4 including Jupyter-TensorBoard
# TransformerEngine 1.14
# TensorRT Model Optimizer 0.21
ARG LMDEPLOY_VERSION
ENV LMDEPLOY_VERSION=${LMDEPLOY_VERSION}
RUN echo "Stage 1 LMDEPLOY_VERSION: ${LMDEPLOY_VERSION}"

# Set environment variables
ENV TZ=Asia/Shanghai
ENV LOG_LEVEL=INFO
ENV CUDA_VISIBLE_DEVICES=0
ENV WRITE_WHL="true"

# Copy necessary files
COPY ./../ /ant_lmdeploy
COPY ./../builder/manywheel/entrypoint_build_ngc.sh /entrypoint_build.sh
# COPY ./../requirements/ngc-build.txt /tmp/requirements-ngc-build.txt
# RUN pip3 install --no-cache-dir -r /tmp/requirements-ngc-build.txt --index-url https://pypi.tuna.tsinghua.edu.cn/simple
# Build the WHL file
RUN sh /entrypoint_build.sh

# List contents of /tmpbuild for debugging
RUN ls -la /tmpbuild/

# Verify the WHL file
RUN WHL_FILE=$(ls /tmpbuild/lmdeploy-${LMDEPLOY_VERSION}*.whl) && \
    echo "Found WHL file: ${WHL_FILE}"

# List contents of /lmdeploy_build for debugging
RUN ls -la /lmdeploy_build/

# Stage 2: Create a minimal stage to copy the WHL file
FROM scratch AS exporter
COPY --from=builder /lmdeploy_build/*.whl .

# Stage 3: Create the final image
FROM nvcr.io/nvidia/pytorch:25.01-py3

ARG LMDEPLOY_VERSION
ENV LMDEPLOY_VERSION=${LMDEPLOY_VERSION}

# Set CUDA architecture list
ARG torch_cuda_arch_list='7.0 7.5 8.0 8.6 8.9 9.0+PTX'
ENV TORCH_CUDA_ARCH_LIST=${torch_cuda_arch_list}

# Install dependencies
COPY ./../requirements/ngc-build.txt /workspace/requirements-ngc-build.txt
RUN pip3 install -r /workspace/requirements-ngc-build.txt

# Display detailed information about the LMDEPLOY_VERSION for verification
RUN echo "Stage 3 LMDEPLOY_VERSION: ${LMDEPLOY_VERSION}" && \
    echo "Current CUDA architecture list: ${TORCH_CUDA_ARCH_LIST}" && \
    echo "Environment variables set: TZ=${TZ}, LOG_LEVEL=${LOG_LEVEL}, CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}, WRITE_WHL=${WRITE_WHL}"

# Copy and install the WHL file
COPY --from=builder /tmpbuild/lmdeploy-${LMDEPLOY_VERSION}*.whl /workspace/

# Ensure the WHL file is correctly specified
RUN WHL_FILE=$(ls /workspace/lmdeploy-${LMDEPLOY_VERSION}*.whl) && \
    echo "Installing WHL file: ${WHL_FILE}" && \
    if [ -n "$WHL_FILE" ]; then pip3 install "$WHL_FILE" --no-deps; else echo "No WHL file found"; exit 1; fi

 # # Install triton
# RUN pip3 install triton==2.1.0

WORKDIR /workspace


# Example build commands

# Step 1: If not in the docker directory, navigate to it first
# cd docker

# Step 2: Build and export the WHL file locally
# This step builds the WHL file and exports it to the local ./lmdeploy_build directory
# time DOCKER_BUILDKIT=1 docker build --progress=plain --platform linux/amd64 --build-arg LMDEPLOY_VERSION=0.9.0.1   --target exporter --output type=local,dest=./lmdeploy_build -f Dockerfile_ngc ..

# Step 3: Build the final image
# This step builds the complete image, including installing the WHL file
# time DOCKER_BUILDKIT=1 docker build --progress=plain --platform linux/amd64 -t ant_lmdeploy:v0.9.0.1_cu128_$(date +"%Y%m%d") --build-arg LMDEPLOY_VERSION=0.9.0.1 -f Dockerfile_ngc ..
